In [1]:
# Got the mobile price classification dataset from kaggle.com
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
import numpy as np 
import pandas as pd

In [2]:
data=pd.read_csv('train.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [3]:
X = data.drop('price_range',axis=1)
X.shape

(2000, 20)

In [4]:
y=data['price_range']
y.shape

(2000,)

## Selecting the top 10 features using chi2 method

In [5]:
# selecting the top ten features
best_features = SelectKBest(score_func=chi2,k=10).fit(X,y)

In [6]:
# now we are applying our SelectKBest on our training data
feature_score = best_features.fit(X,y)

In [7]:
# Now we will get the importance of each feature in terms of numbers
feature_score = feature_score.scores_

In [8]:
feature_score

array([1.41298666e+04, 7.23232323e-01, 6.48365906e-01, 6.31010795e-01,
       1.01351665e+01, 1.52157239e+00, 8.98391244e+01, 7.45819631e-01,
       9.59728626e+01, 9.09755558e+00, 9.18605355e+00, 1.73635695e+04,
       9.81058675e+03, 9.31267519e+05, 9.61487832e+00, 1.64803191e+01,
       1.32364000e+01, 3.27642810e-01, 1.92842942e+00, 4.22090730e-01])

In [9]:
df_scores = pd.DataFrame(data = feature_score)
df_scores

0
0    14129.866576
1        0.723232
2        0.648366
3        0.631011
4       10.135166
5        1.521572
6       89.839124
7        0.745820
8       95.972863
9        9.097556
10       9.186054
11   17363.569536
12    9810.586750
13  931267.519053
14       9.614878
15      16.480319
16      13.236400
17       0.327643
18       1.928429
19       0.422091

In [10]:
df_columns = X.columns
df_columns = pd.DataFrame(data = df_columns)
df_columns

0
0   battery_power
1            blue
2     clock_speed
3        dual_sim
4              fc
5          four_g
6      int_memory
7           m_dep
8       mobile_wt
9         n_cores
10             pc
11      px_height
12       px_width
13            ram
14           sc_h
15           sc_w
16      talk_time
17        three_g
18   touch_screen
19           wifi

In [11]:
df_feature_score = pd.concat([df_columns,df_scores],axis=1)
df_feature_score.columns=['Features','Importance_Score']
df_feature_score

Features  Importance_Score
0   battery_power      14129.866576
1            blue          0.723232
2     clock_speed          0.648366
3        dual_sim          0.631011
4              fc         10.135166
5          four_g          1.521572
6      int_memory         89.839124
7           m_dep          0.745820
8       mobile_wt         95.972863
9         n_cores          9.097556
10             pc          9.186054
11      px_height      17363.569536
12       px_width       9810.586750
13            ram     931267.519053
14           sc_h          9.614878
15           sc_w         16.480319
16      talk_time         13.236400
17        three_g          0.327643
18   touch_screen          1.928429
19           wifi          0.422091

In [12]:
df_feature_score = df_feature_score.sort_values(by=['Importance_Score'],ascending = False)

In [13]:
df_feature_score

Features  Importance_Score
13            ram     931267.519053
11      px_height      17363.569536
0   battery_power      14129.866576
12       px_width       9810.586750
8       mobile_wt         95.972863
6      int_memory         89.839124
15           sc_w         16.480319
16      talk_time         13.236400
4              fc         10.135166
14           sc_h          9.614878
10             pc          9.186054
9         n_cores          9.097556
18   touch_screen          1.928429
5          four_g          1.521572
7           m_dep          0.745820
1            blue          0.723232
2     clock_speed          0.648366
3        dual_sim          0.631011
19           wifi          0.422091
17        three_g          0.327643

In [14]:
new_X = df_feature_score.head(10)['Features'].values
new_X

array(['ram', 'px_height', 'battery_power', 'px_width', 'mobile_wt',
       'int_memory', 'sc_w', 'talk_time', 'fc', 'sc_h'], dtype=object)

In [15]:
X = X[new_X]
X

ram  px_height  battery_power  px_width  mobile_wt  int_memory  sc_w  \
0     2549         20            842       756        188           7     7   
1     2631        905           1021      1988        136          53     3   
2     2603       1263            563      1716        145          41     2   
3     2769       1216            615      1786        131          10     8   
4     1411       1208           1821      1212        141          44     2   
...    ...        ...            ...       ...        ...         ...   ...   
1995   668       1222            794      1890        106           2     4   
1996  2032        915           1965      1965        187          39    10   
1997  3057        868           1911      1632        108          36     1   
1998   869        336           1512       670        145          46    10   
1999  3919        483            510       754        168          45     4   

      talk_time  fc  sc_h  
0            19   1     9  
1             7   0    17  
2             9   2    11  
3            11   0    16  
4            15  13     8  
...         ...  ..   ...  
1995         19   0    13  
1996         16   0    11  
1997          5   1     9  
1998         19   4    18  
1999          2   5    19  

[2000 rows x 10 columns]

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
rfc = RandomForestClassifier()

In [19]:
model = rfc.fit(X,y)

In [20]:
test_data = pd.read_csv('test.csv')
test_data

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0      0.1        193  ...  16        226      1412  3476    12     7   
1      0.8        191  ...  12        746       857  3895     6     0   
2      0.9        186  ...   4       1270      1366  2396    17    10   
3      0.5         96  ...  20        295      1752  3893    10     0   
4      0.5        108  ...  18        749       810  1773    15     8   
..     ...        ...  ...  ..        ...       ...   ...   ...   ...   
995    0.5        170  ...  17        644       913  2121    14     8   
996    0.9        186  ...   2       1152      1632  1933     8     1   
997    0.5         80  ...  12        477       825  1223     5     0   
998    0.4        171  ...  12         38       832  2509    15    11   
999    0.1        140  ...  19        457       608  2828     9     2   

     talk_time  three_g  touch_screen  wifi  
0            2        0             1     0  
1            7        1             0     0  
2           10        0             1     1  
3            7        1             1     0  
4            7        1             0     1  
..         ...      ...           ...   ...  
995         15        1             1     0  
996         19        0             1     1  
997         14        1             0     0  
998          6        0             1     0  
999          3        1             0     1  

[1000 rows x 21 columns]

In [21]:
test_X = test_data[new_X]

In [22]:
test_X

ram  px_height  battery_power  px_width  mobile_wt  int_memory  sc_w  \
0    3476        226           1043      1412        193           5     7   
1    3895        746            841       857        191          61     0   
2    2396       1270           1807      1366        186          27    10   
3    3893        295           1546      1752         96          25     0   
4    1773        749           1434       810        108          49     8   
..    ...        ...            ...       ...        ...         ...   ...   
995  2121        644           1700       913        170          54     8   
996  1933       1152            609      1632        186          13     1   
997  1223        477           1185       825         80           8     0   
998  2509         38           1533       832        171          50    11   
999  2828        457           1270       608        140          35     2   

     talk_time  fc  sc_h  
0            2  14    12  
1            7   4     6  
2           10   1    17  
3            7  18    10  
4            7  11    15  
..         ...  ..   ...  
995         15   0    14  
996         19   0     8  
997         14   1     5  
998          6   0    15  
999          3   4     9  

[1000 rows x 10 columns]

In [23]:
predictions = model.predict(test_X)
predictions

array([3, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 0, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 3, 0, 3, 1, 3, 1, 1, 3, 3, 2, 0, 1, 1, 1,
       1, 2, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 2, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 2, 2, 0, 2, 1, 0, 2, 1, 2, 1, 0, 0, 3, 1, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 1, 3, 0, 0, 3, 2, 1, 1, 0, 3, 2, 3, 1, 0, 2,
       1, 1, 3, 1, 1, 0, 3, 2, 1, 3, 1, 2, 2, 3, 3, 2, 2, 3, 2, 3, 1, 0,
       3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 3, 2, 0, 2, 2,
       2, 3, 1, 2, 3, 3, 3, 2, 2, 1, 0, 0, 1, 2, 0, 2, 3, 3, 0, 2, 0, 3,
       2, 2, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 3, 1, 2, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 1, 2, 3, 1, 1, 3, 2, 0, 3, 0, 1, 2, 0, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 2, 2, 1, 2, 0, 2, 3, 1,

In [24]:
len(predictions)

1000

In [25]:
model.predict([[3,1440,3000,720,145,32,6,6,5,5]])

array([0], dtype=int64)